project:
  type: website

website:
  title: "Nolan Penoyer Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Introduction.qmd
        text: Introduction
      - href: DataGathering.qmd
        text: Data Gathering
      - href: DataCleaning.qmd
        text: Data Cleaning
      - href: DataExploration.qmd
        text: Data Exploration
      - href: Clustering.qmd
        text: Clustering
      - href: DimensionalityReduction.qmd
        text: Dimensionaility Reduction
      - href: DecisionTrees.qmd
        text: Decision Trees
      - href: ARM.qmd
        text: ARM
      - href: Conclusions.qmd
        text: Conclusions

bibliography: "reference.bib"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



