---
title: "Introduction"
---

# Housing Trends
In every aspect of life, discovering insights before others can give us a competitive advantage that will allow us to get ahead. In some activities we do, although we may know information others do not, the nature of the framework we are operating in may restrict how much utility we gain. For example, knowing the opponents next move in a game of checkers will only give us the satisfaction of winning the checkers game. However, other information is much more valuable because of the gravity of the affair in the larger scheme of life.

Shelter is a need that every human must have fulfilled. In the United States, 66% of Americans are home owners. These homeowners on average have 70% of their net worth invested into their home. Real estate can also be highly profitable for those wanting to create cash flow from owning homes or mulitifamily homes. Therefore, it is easy to see that the housing market is one area where having insights that others do not have, like housing trends in a certain city, will give us a multitude of utility. I would like to buy a multifamily home after I graduate; if I knew what areas would provide me with consistent tenants and a property that goes up in value, I would be very much ahead of the game in the real estate realm and in life in general.

In this project, I will use census data to attempt to reveal housing trends in a certain city.


# What Has Already Been Done

In *The Winners in China’s Urban Housing Reform*, the researchers used census data to reveal who benefited from China's housing reform that privatized public housing. With the census data, they were able to estimate the housing subsidy received by renters in the public sector by examining private sector prices of houses of comparable quality and size. The census data contained information on six modes of housing tenure that could be compared and contained information on housing characteristics like housing space, number of bathrooms, ect. @doi:10.1080/02673030903240660. Although this study has a different end goal than me, I will use census data in a similar way to try to estimate housing prices.

In *House Price Prediction Using Regression Techniques: A Comparative Study*, the researchers attempt to forecast housing prices using different predictive techniques like multiple linear regression, LASSO, and gradient boosting among others @8882834. I could potentially use the same techniques to accomplish my goals.

# Questions I want to Answer

* Which variable in census data reveals the most about the direction of housing prices in a certain area?
* How do demographic trends play a role?
* Does age have an impact?
* Does sex have an impact?
* Does race have an impact?
* Does school enrollment have an impact?
* Does migration data tell most of the story?
* How much are home prices impacted by trends in population?
* Can we predict which areas to invest in in a certain city?
* Can we predict which areas are the best for landlords to have a steady flow of tenants?
